version: '3.8'

services:
  nextjs:
    image: arthurheukocibokunc/to-do-list-app:1.0
    container_name: to-do-list-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    networks:
      - mysql-net

networks:
  mysql-net:
    external: true
